# Dependencies
markdown:         kramdown

kramdown:
  syntax_highlighter: rouge

# gems:
  # - jemoji

plugins:
  - jemoji
  - jekyll-tabs

permalink: news/:title/

# Collections
collections:
- doc

collections:
  doc:
    output: true
    permalink: doc/:path/



# Setup
title:            GDX2D
tagline:          'A gaming library'
description:      'A gaming library for <a href="http://isc.hevs.ch" title="ISC" target="_blank">ISC</a>.'
url:              https://isc-hei.github.io/gdx2d/
baseurl:          /gdx2d

author:
  name:           'Pierre-André Mudry'
  url:            http://www.hevs.ch/isc

# Custom vars

# Latest libGDX version
# The download link is '{{ site.github.repo }}archive/v{{ site.github.latestversion }}.zip'
github:
  latestversion: 1.2.2
  repo:          https://github.com/ISC-HEI/gdx2d/
